docs: note gotcha with `yarn add` and possible workaround
Two days in a row now I've had trouble building the
frontend-editor-ckeditor-web module in liferay-portal after a `yarn
add`. Yesterday it was freaking out with:

```
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
        [class java.lang.String, class java.lang.String]
        [class java.io.File, class java.lang.String]
```

caused by `packageRunBuild.destinationDir` in the build.gradle file
somehow being `null`.

Today, it's:

```
Error: ENOENT: no such file or directory, open 'node_modules/liferay-ckeditor/package.json'
    at Object.openSync (fs.js:439:3)
 ```

Yet, when I inspect the `node_modules` folder everything is golden.

In both cases, things work fine when I do then manual `cp -R` instead of
the `yarn add`. Whatever the cause, may as well document the workaround.